security:
    encoders:
        Symfony\Component\Security\Core\User\User:
                algorithm:   sha1
                iterations: 1
                encode_as_base64: false
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    oumnia:
                        password: 4c6e5f663c90053b61c94ad5401d35e45b56a388
                        roles: 'ROLE_USER'
                    admin:
                        password: d033e22ae348aeb5660fc2140aec35850c4da997
                        roles: 'ROLE_ADMIN'
    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path:            /index
            logout:
                path:   fos_user_security_logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/index, role: ROLE_USER, requires_channel: https }
        - { path: ^/admin, role: ROLE_ADMIN , requires_channel: https}
        - { path: ^/, role: ROLE_USER , requires_channel: https}